#!/usr/bin/env python3
"""
Build Bunny's animation states from source GIFs.

This is the ONLY step required to add a new state to the plugin:

    1. Drop a GIF into bunny/assets/source_gifs/<state_id>.gif
       (state_id becomes the internal name; use lowercase + underscores,
       e.g. "eating.gif", "playing.gif", "sleeping.gif", "grooming.gif")
    2. Run this script:  python3 tools/build_states.py
    3. Commit the generated bunny/assets/states/<state_id>/ folder.

That's it — bunny.luau has no hardcoded state list. At runtime it reads
bunny/assets/states/manifest.json (regenerated by this script every run)
and cycles through whatever states exist there, in the order listed.

Why this exists at all: Noctalia's widget image element (barWidget.setImage
/ ui.image) only displays static images — there is no built-in "play this
animated GIF" API (confirmed against noctalia.d.luau and the v5 plugin
docs). So each GIF is decomposed once, at build time, into a numbered PNG
frame sequence + a small timing manifest, and bunny.luau does the frame
cycling itself at runtime (the same technique the original bunny.luau used
for its hand-drawn animations, just now driven by real source GIFs instead
of hand-authored frame folders).

Requires: pip install Pillow --break-system-packages
"""

import json
import sys
from pathlib import Path

try:
    from PIL import Image, ImageSequence
except ImportError:
    print("Pillow is required: pip install Pillow --break-system-packages", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "bunny" / "assets"
SOURCE_DIR = ASSETS / "source_gifs"
STATES_DIR = ASSETS / "states"

# Optional per-state overrides, keyed by state id (the gif's filename stem).
# Only needed if you want a display label different from the auto-generated
# "Title Case" of the filename, or a custom tooltip. Everything else is
# fully automatic. Safe to leave empty — new states work with zero entries.
OVERRIDES = {
    # "eating": {"label": "Eating"},
}


def label_for(state_id: str) -> str:
    override = OVERRIDES.get(state_id, {})
    if "label" in override:
        return override["label"]
    return state_id.replace("_", " ").replace("-", " ").title()


def build_state(gif_path: Path) -> dict:
    state_id = gif_path.stem
    out_dir = STATES_DIR / state_id
    out_dir.mkdir(parents=True, exist_ok=True)

    # Clear any previously-generated frames for this state so removed/renamed
    # frames from a re-exported GIF don't linger.
    for old in out_dir.glob("frame_*.png"):
        old.unlink()

    im = Image.open(gif_path)
    frame_count = 0
    delays = []
    width = height = 0

    for frame in ImageSequence.Iterator(im):
        rgba = frame.convert("RGBA")
        width, height = rgba.size
        rgba.save(out_dir / f"frame_{frame_count:03d}.png")
        delays.append(frame.info.get("duration", 100) or 100)
        frame_count += 1

    if frame_count == 0:
        raise ValueError(f"{gif_path} has no frames")

    # A single shared delay keeps bunny.luau's per-state timing table small;
    # GIFs with genuinely per-frame-varying delays still animate fine using
    # the average (looping evens it out over one cycle).
    avg_delay_ms = round(sum(delays) / len(delays))

    meta = {
        "id": state_id,
        "label": label_for(gif_path.stem),
        "frame_count": frame_count,
        "frame_delay_ms": avg_delay_ms,
        "width": width,
        "height": height,
    }
    (out_dir / "meta.json").write_text(json.dumps(meta, indent=2) + "\n")
    return meta


def main():
    if not SOURCE_DIR.exists():
        print(f"No source_gifs directory at {SOURCE_DIR}", file=sys.stderr)
        sys.exit(1)

    gifs = sorted(SOURCE_DIR.glob("*.gif"))
    if not gifs:
        print(f"No .gif files found in {SOURCE_DIR}", file=sys.stderr)
        sys.exit(1)

    STATES_DIR.mkdir(parents=True, exist_ok=True)

    manifest_states = []
    kept_dirs = set()
    for gif_path in gifs:
        meta = build_state(gif_path)
        kept_dirs.add(meta["id"])
        manifest_states.append(meta["id"])
        print(f"  built '{meta['id']}': {meta['frame_count']} frames, "
              f"{meta['frame_delay_ms']}ms/frame, {meta['width']}x{meta['height']}")

    # Prune stale state folders whose source GIF was removed/renamed.
    for existing in STATES_DIR.iterdir():
        if existing.is_dir() and existing.name not in kept_dirs:
            print(f"  removing stale state '{existing.name}' (no matching source gif)")
            for f in existing.glob("*"):
                f.unlink()
            existing.rmdir()

    manifest = {"states": manifest_states}
    (STATES_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"\nWrote manifest with {len(manifest_states)} state(s): {', '.join(manifest_states)}")


if __name__ == "__main__":
    main()
